twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ps: '@App\Twig\PatientStatistiques'
        myOps: '@App\Service\MyOps'
    form_themes: ['bootstrap_4_layout.html.twig','@TetranzSelect2Entity/Form/fields.html.twig']

when@test:
    twig:
        strict_variables: true
